# Generated by Django 6.0.2 on 2026-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor')], default='student', max_length=20),
        ),
    ]
