# Generated by Django 6.0.2 on 2026-04-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_options'),
        ('users', '0003_customuser_role_certificate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_user_opportunity_certificate'),
        ),
    ]
