# Generated by Django 6.0.2 on 2026-05-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, help_text='Write interests separated by commas, e.g. teaching, environment, community', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
