# Generated by Django 6.0.3 on 2026-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('volunteer_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
