# Generated by Django 6.0.2 on 2026-04-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('opportunities', '0002_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
            preserve_default=False,
        ),
    ]
