# Generated by Django 6.0.2 on 2026-04-22 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_opportunity'),
        ('opportunities', '0002_alter_opportunity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'opportunity'), name='unique_student_opportunity_application'),
        ),
    ]
