# Generated by Django 6.0.3 on 2026-03-09 00:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('education', 'التعليم'), ('health', 'الصحة والرعاية'), ('environment', 'البيئة'), ('community', 'خدمة المجتمع'), ('arts', 'الفنون والثقافة'), ('sports', 'الرياضة'), ('technology', 'التكنولوجيا'), ('other', 'آخرى')], max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#667eea', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_opportunities', models.IntegerField(default=0)),
                ('total_certificates', models.IntegerField(default=0)),
                ('impact_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Impacts',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('beginner', 'سهل'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20)),
                ('max_volunteers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('requirements', models.TextField(blank=True, help_text='المتطلبات المطلوبة')),
                ('skills', models.CharField(blank=True, help_text='المهارات المطلوبة (مفصولة بفواصل)', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('bronze', 'برونزي'), ('silver', 'فضي'), ('gold', 'ذهبي'), ('platinum', 'بلاتيني')], default='bronze', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='volunteers.opportunity')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='volunteers.organization'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='volunteers.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='volunteers.opportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('date_completed', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_hours', to='volunteers.opportunity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hours', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='سبب الرفض إن وجد')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='volunteers.opportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'start_date'], name='volunteers__status_23f474_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization', 'status'], name='volunteers__organiz_4b01e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('volunteer', 'opportunity')},
        ),
        migrations.AddIndex(
            model_name='volunteerhours',
            index=models.Index(fields=['volunteer', 'status'], name='volunteers__volunte_144814_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerhours',
            index=models.Index(fields=['date_completed'], name='volunteers__date_co_5c1dd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerregistration',
            unique_together={('volunteer', 'opportunity')},
        ),
    ]
